# Generated by Django 4.0.4 on 2022-08-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='is_patient',
            field=models.BooleanField(default=True),
        ),
    ]
