# Generated by Django 4.0.4 on 2022-08-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_blogmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
