# Generated by Django 4.0.4 on 2022-08-24 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0006_alter_blogmodel_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(choices=[('MH', 'Mental health'), ('C19', 'Covid19'), ('HD', 'Heart Disease'), ('IM', 'Immunization')], max_length=200),
        ),
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apppoint_date', models.DateField()),
                ('appoint_time', models.TimeField()),
                ('discription', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appoint', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appoint', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
