# Generated by Django 4.0.4 on 2022-08-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_blogmodel_category_bookappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
